name: build

on: [ push, pull_request, workflow_dispatch ]

env:
  NODE_VERSION: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install -g yarn

      - name: Build docs
        run: yarn install && yarn build:docs

      - name: Commit build
        run: |
          git add "./docs"
          git config --global user.name 'mineejo'
          git config --global user.email 'mineejo@users.noreply.github.com'
          git commit -am "chore(build): automatic documentation builder"
          git push
